- Makefile
- README.md
- api/v1alpha1/pool_types_test.go
- api/v1alpha1/pool_webhook.go
- go.mod
in garm, a pool is uniq on imageName, flavor, provider and scope. This fixes the current implementation where we compared the image.tag name with the name of the image referenc itself.
fixes https://github.com/mercedes-benz/garm-operator/issues/2
> fix: reject pool creation if pool with spec exists

- .github/ISSUE_TEMPLATE/feature.yaml
- README.md
Beside the https://doc.crds.dev/github.com/mercedes-benz/garm-operator link in the CRD section we will 
also get a badge for the mandatory `build, lint and test` action:
> docs: add crds.dev link to visualize current CRD

- api/v1alpha1/image_webhook.go
- api/v1alpha1/pool_webhook.go
For pools with a deletion timestamp it's fine to not track this pool where the image is in use.
> feat: allow image deletion for deleted pools

- api/v1alpha1/image_webhook.go
- api/v1alpha1/pool_webhook.go
if a pool has a deletionTimestamp set, it's fine to not validate the pool-CR again to force the deletion of the CR
```
I1025 12:38:29.101801       1 image_webhook.go:33] image-resource "msg"="validate create" "name"="runner-default-mario"
I1025 12:38:32.684946       1 pool_webhook.go:41] pool-resource "msg"="validate create" "name"="mario01"
I1025 12:38:33.376533       1 pool_webhook.go:88] pool-resource "msg"="validate update" "name"="mario01" "namespace"="garm-infra-stage-int"
I1025 12:38:33.376584       1 pool_webhook.go:147] pool-resource "msg"="validate spec.providerName" "spec.providerName"="os02.fra-prod3"
I1025 12:38:33.376596       1 pool_webhook.go:177] pool-resource "msg"="validate spec.githubScopeRef" "spec.githubScopeRef"={"apiGroup":"garm-operator.mercedes-benz.com","kind":"O …
```
> feat: allow image deletion for in-deleting pools

- docs/config/configuration-parsing.md
fixes incorrect reference of markdown anchor in configuration parsing documentation
> docs: fix anchor in configuration parsing documentation

- DEVELOPMENT.md
- Dockerfile
- Tiltfile
- config/manager/manager.yaml
- config/overlays/debug/kustomization.yaml
- config/overlays/debug/manager_patch.yaml
- config/overlays/local/manager_patch.yaml
document the steps to attach `delve` to a running garm-operator within the local kind-cluster
> docs: describe local debug via delve

- .github/workflows/release.yml
- .goreleaser.yaml
Blackduck seems to be "stable" again - so let's enable it for new versions again. It's already active on main
> chore: enable blackduck scan on version build

- internal/controller/enterprise_controller.go
- internal/controller/organization_controller.go
- internal/controller/pool_controller.go
- internal/controller/repository_controller.go
- internal/controller/runner_controller.go
- pkg/client/key/key.go
- pkg/util/annotations/helpers.go
Every time  a controller attempts to reconcile a CR, the last-sync-time annotation gets updated.
> feat: add lastSyncTime annotation to CRs

- .github/workflows/build.yml
as we do the PR title validation in a dedicated action, we can get rid of this orphaned nodejs setup step during build
> chore: remove nodejs from build action

- .github/workflows/build.yml
- .github/workflows/release.yml
- .goreleaser.yaml
- Makefile
As blackduck is still not stable - let's generate the SBOM with `kubernetes-sigs/bom`
> feat: generate SBOM via kubernetes-sigs/bom

- cmd/main.go
- go.mod
- go.sum
- pkg/client/client.go
- pkg/metrics/metrics.go
Parses jwt and exposes expiry date to prometheus like the following:
```
garm_operator_info_jwt_expires_at{controller="garm_operator"} 1.737204962e+09
```
With a grafana field override, the gauge value can be visualized like so:
> feat: expose jwt exp date as metric

- internal/controller/enterprise_controller.go
- internal/controller/enterprise_controller_test.go
- internal/controller/organization_controller.go
- internal/controller/organization_controller_test.go
- internal/controller/pool_controller.go
- internal/controller/pool_controller_test.go
- internal/controller/repository_controller.go
- internal/controller/repository_controller_test.go
- internal/controller/runner_controller.go
- internal/controller/runner_controller_test.go
- pkg/util/annotations/helpers.go
removes last-sync-time annotation which should prevent countless unnecessary reconciles to be triggered.
> fix: remove last-sync-time annotation

- .github/dependabot.yml
- Makefile
- hack/kind-with-registry.sh
as there are few more things to do when updating
k8s.io/controller-runtime (e.g. using the same version in kind cluster - relevant when we start with integration tests) we will disable the dump dependabot update PRs
> chore: disable automatic k8s.io package updates

- config/kube-state-metrics/configmap.yaml
also introduce pool_min_idle_runners, pool_max_runners, status_long_running_idle_runners
and add namespace as label per metric
> feat: pool enabled status as dedicated metric

- internal/controller/runner_controller.go
fix should have been in 0.3.0 release
https://github.com/mercedes-benz/garm-operator/pull/113/files#diff-93df91d9269bd31cc29ac5ba24b171a95bf84f12d51bc82ab4031ee47332b852L233-L236
> fix: runner-deletion

- .github/workflows/build.yml
- .github/workflows/foss.yaml
- .github/workflows/pull-request-lint.yml
- .github/workflows/release.yml
- hack/foss-scan.sh
- hack/generate-notices-file.sh
fixes #160 
- New generation of notices file with copyright info which is required by our FOSS guidluines
- pin actions to specific sha version
> fix: foss scan

- api/v1beta1/githubendpoint_types.go
- config/crd/bases/garm-operator.mercedes-benz.com_githubendpoints.yaml
it's not possible to create a githubendpoint configuration with the name github.com
This is because garm ships a default githubendpoint configuration which is immutable.
fixes #187
> feat: block the creation of github.com endpoint

- cmd/main.go
- go.mod
- go.sum
- pkg/version/version.go
- pkg/version/version_test.go
fixes #170 
the version string get's extracted from the controller-info endpoint. And to make use of this endpoint, the garm server doesn't need to be initialized.
> feat: error early if min. supported version match

- Tiltfile
- api/v1beta1/garmserverconfig_types.go
- api/v1beta1/githubcredentials_types.go
- api/v1beta1/githubendpoint_types.go
- config/crd/bases/garm-operator.mercedes-benz.com_garmserverconfigs.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_githubcredentials.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_githubendpoints.yaml
- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_githubcredentials.yaml
- config/crd/patches/webhook_in_githubcredentials.yaml
- config/rbac/githubcredentials_editor_role.yaml
- config/rbac/githubcredentials_viewer_role.yaml
this pr will fix a few missing `githubcredentials` (plural) occurences.
It also drops short names for `garmserverconfig` (which was `server`), `githubcredentials` (which was `creds`) and `githubendpoints` (which was `gep`).
> fix: add missing githubcredentials plural occurences

- api/v1alpha1/enterprise_types.go
- api/v1alpha1/image_types.go
- api/v1alpha1/organization_types.go
- api/v1alpha1/pool_types.go
- api/v1alpha1/repository_types.go
- api/v1alpha1/runner_types.go
- config/crd/bases/garm-operator.mercedes-benz.com_enterprises.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_images.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_organizations.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_pools.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_repositories.yaml
- config/crd/bases/garm-operator.mercedes-benz.com_runners.yaml
We will mark `v1alpha1` as deprecated.
```bash
kubectl apply -f tmp/flux-dev-pool.yaml 
Warning: This version is deprecated. Use v1beta1 instead.
pool.garm-operator.mercedes-benz.com/flux created
```
Signed-off-by: Mario Constanti <mario.constanti@mercedes-benz.com>
> feat: mark v1alpha1 as deprecated

- config/kube-state-metrics/configmap.yaml
removed whitespaces in kube-state-metrics configmap, because a lot of new lines where created which made the configmap almost unreadable
> fix(ksm): remove whitespaces in cm

- pkg/client/client.go
- pkg/client/controller.go
to make garm work after the initialization, we apply a default config for webhookURL, metadataURL and callbackURL
this config will be overwritten once a garmserverconfig CR got applied
during the initial start of garm with the operator, the `controller info` will look like:
```bash
+-------------------------+-------------------------------------------------------------------------+
| FIELD                   | VALUE                                                                   |
+-------------------------+-------------------------------------------------------------------------+
| Controller ID           | dd2524b9-0789-499d-ba7d-3dba65cf9d3f                                    |
| Hostname                | garm-server-7c9d8f57b6-54zt2                                            |
| …
```
> fix: apply a dummy default controller config

- config/samples/garm-operator_v1beta1_pool.yaml
- config/samples/garm-operator_v1beta1_repository.yaml
- internal/controller/enterprise_controller.go
- internal/controller/enterprise_controller_test.go
- internal/controller/githubcredentials_controller.go
- internal/controller/githubcredentials_controller_test.go
- internal/controller/githubendpoint_controller.go
- internal/controller/githubendpoint_controller_test.go
- internal/controller/organization_controller.go
- internal/controller/organization_controller_test.go
- internal/controller/pool_controller.go
- internal/controller/pool_controller_test.go
- internal/controller/repository_controller.go
- internal/controller/repository_controller_test.go
- pkg/client/key/key.go
- pkg/finalizers/finalizers.go
by setting the finalizer on pool level, it's necessary to immediately end the reconciliation loop and add the pool CR back to the reconciliation loop. Otherwise the reconciliation will continue and a parallel reconciliation will happen where the pool status (with the pool id) is still empty - which leads to another pool creation
> fix: dublicate pool creation

- api/v1beta1/githubendpoint_types.go
- config/crd/bases/garm-operator.mercedes-benz.com_githubendpoints.yaml
- docs/adrs/github_default_endpoint.md
As garm has removed the restriction for immutable github.com named github-endpoints, there is no need to keep this restriction in the operator as well.
closes #267
> feat: allow GithubEndpoint object named github.com
